# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ordinary Least Squares
#' 
#' Fits the standard OLS model.
#' 
#' @param y Numeric vector.
#' @param X Numeric matrix.
#' 
#' @return List containing the following:
#' \item{Beta}{Regression coefficient.}
#' \item{V}{Outcome variance.}
#' \item{Ibb}{Information matrix for beta.}
#' \item{Resid}{Outcome residuals.}
#' 
fitOLS <- function(y, X) {
    .Call(`_BNR_fitOLS`, y, X)
}

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar.
tr <- function(A) {
    .Call(`_BNR_tr`, A)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
MMP <- function(A, B) {
    .Call(`_BNR_MMP`, A, B)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
matIP <- function(A, B) {
    .Call(`_BNR_matIP`, A, B)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix. 
matInv <- function(A) {
    .Call(`_BNR_matInv`, A)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar. 
det <- function(A) {
    .Call(`_BNR_det`, A)
}

#' Fast Outer Product
#' 
#' Calculates the outer product \eqn{XY'}.
#' 
#' @param X Numeric matrix.
#' @param Y Numeric matrix.
#' @return Numeric matrix.
matOP <- function(X, Y) {
    .Call(`_BNR_matOP`, X, Y)
}

#' Quadratic Form
#' 
#' Calculates the quadratic form \eqn{X'AX}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @return Numeric matrix. 
matQF <- function(X, A) {
    .Call(`_BNR_matQF`, X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{bb}-I_{ba}I_{aa}^{-1}I_{ab}}. 
#'
#' @param Ibb Information of target parameter
#' @param Iaa Information of nuisance parameter
#' @param Iba Cross information between target and nuisance parameters
#' @return Numeric matrix. 
SchurC <- function(Ibb, Iaa, Iba) {
    .Call(`_BNR_SchurC`, Ibb, Iaa, Iba)
}

